/* POPULATE TABLE POST*/

insert into posts (id,title,category,creation_date,body) values (1,"Post sobre spring-boot","spring-boot","2021-04-1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
insert into posts (id,title,category,creation_date,body) values (2,"Otro más sobre spring-boot","spring-boot","2021-04-2", "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
insert into posts (id,title,category,creation_date,body) values (3,"Uno sobre java 16","java","2021-04-3", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.");
insert into posts (id,title,category,creation_date,body) values (4,"Hibernate or die!","hibernate","2021-04-4", "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular.");
insert into posts (id,title,category,creation_date,body) values (5,"Este es sobre las hojas de tomillo","thymeleaf","2021-04-5", "Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.");
insert into posts (id,title,category,creation_date,body) values (6,"Que interesante esto","spring-boot","2021-04-6", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
insert into posts (id,title,category,creation_date,body) values (7,"Spring-boot para todos","spring-boot","2021-04-7", "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
insert into posts (id,title,category,creation_date,body) values (8,"Java rocks!","java","2021-04-8", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.");
insert into posts (id,title,category,creation_date,body) values (9,"Todos odiamos hibernet","hibernate","2021-04-9", "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular.");
insert into posts (id,title,category,creation_date,body) values (10,"Escuchame thymeleaf ¿cuál es tu problema?","thymeleaf","2021-04-10", "Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.");
insert into posts (id,title,category,creation_date,body) values (11,"Novedades Spring","spring-boot","2021-04-11", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
insert into posts (id,title,category,creation_date,body) values (12,"Un spring-boot no hace primavera","spring-boot","2021-04-12", "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
insert into posts (id,title,category,creation_date,body) values (13,"Estoy a 15 minutos de pasarme a Kotlin","java","2021-04-13", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.");
insert into posts (id,title,category,creation_date,body) values (14,"Hibernate o no hibernet, esa es la cuestión","hibernate","2021-04-14", "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular.");
insert into posts (id,title,category,creation_date,body) values (15,"Parsley, sage, rosmary, and thyme(leaf)","thymeleaf","2021-04-15", "Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.");
insert into posts (id,title,category,creation_date,body) values (16,"Spring-boot me odia","spring-boot","2021-04-16", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.");
insert into posts (id,title,category,creation_date,body) values (17,"Nah, spring-boot es bueno","spring-boot","2021-04-17", "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
insert into posts (id,title,category,creation_date,body) values (18,"Novedades que traerá java 17","java","2021-04-18", "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.");
insert into posts (id,title,category,creation_date,body) values (19,"Los osos no son los únicos que hibernan","hibernate","2021-04-19", "Li Europan lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc, litot Europa usa li sam vocabular.");
insert into posts (id,title,category,creation_date,body) values (20,"Tomillo, tomillo, tomillo corazón...","thymeleaf","2021-04-20", "Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilite de un nov lingua franca: On refusa continuar payar custosi traductores. At solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.");
