version: '3.7'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blogapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker-mysql
    ports:
      - "3307:3306"
    

  app:
    image: blog_app:latest
    ports:
      - "8080:8080"
    container_name: blogapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/blogapp?autoReconnect=true&useSSL=false&serverTimezone=UTC-3&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin 
    depends_on:
      - db
    links: 
      - db
    
